hyperparameters:
  lr: [0.001]
  optimizers: ["Adam"]
  batchsize: [32]
  reduction_value: [10, 7]
  aggregation_method: None
  prunning_val: [0.5]
dataset:
  name: "CELEBA"
  number_of_classes: 10
options:
  threshold: 0.5
  number_of_trails: 9
  epochs: 200
  device: "cpu"
  name_of_the_run: "LinearModel_Prunned"
  add_reduction_layer: True
  model: "CelebA"
