hyperparameters:
  lr: [0.01, 0.005, 0.001, 0.0005, 0.0001]
  optimizers: ["Adam", "SGD"]
  batchsize: [128]
  reduction_value: [10]
dataset:
  name: "MNIST"
  number_of_classes: 10
options:
  threshold: 0.5
  number_of_trails: 20
  epochs: 2
  device: "cpu"
  name_of_the_run: "ReducionLayerTest"
  add_reduction_layer: True
  model: "LaNet"
