hyperparameters:
  lr: [0.001]
  optimizers: ["Adam"]
  batchsize: [128]
  reduction_value: [10, 9, 8, 7, 6, 5, 4, 3, 2]
dataset:
  name: "MNIST"
  number_of_classes: 10
options:
  threshold: 0.5
  number_of_trails: 20
  epochs: 2
  device: "cpu"
  name_of_the_run: "ReducionLayerOverAll"
  add_reduction_layer: True
  model: "LaNet"
