hyperparameters:
  lr: [0.001]
  optimizers: ["Adam"]
  batchsize: [128]
  reduction_value: [2]
  aggregation_method: None
  prunning_val: [0.0]
dataset:
  name: "MNIST"
  number_of_classes: 11
options:
  threshold: 0.5
  number_of_trails: 2
  epochs: 30
  device: "cpu"
  name_of_the_run: "LinearModel_Prunned"
  add_reduction_layer: True
  model: "LaNet"
