hyperparameters:
  lr: [0.001]
  optimizers: ["Adam"]
  batchsize: [256]
  reduction_value: [8,]
  aggregation_method: "prod"
dataset:
  name: "MNIST"
  number_of_classes: 10
options:
  threshold: 0.5
  number_of_trails: 20
  epochs: 30
  device: "cpu"
  name_of_the_run: "prod_board"
  add_reduction_layer: True
  model: "LaNet"
