hyperparameters:
  lr: [0.001]
  optimizers: ["Adam"]
  batchsize: [128]
  reduction_value: [2, 3, 4, 5, 6, 7, 8, 9, 10]
  aggregation_method: None
  prunning_val: [0]
dataset:
  number_of_classes: 10
  name: "FashionMNIST"
  eval_datasets: ["MNIST",]
options:
  threshold: 0.5
  number_of_trails: 9
  epochs: 5
  device: "cpu"
  name_of_the_run: "FM_to_M"
  add_reduction_layer: True
  model: "LaNet"
