hyperparameters:
  lr: [0.001]
  optimizers: ["Adam"]
  batchsize: [256]
  reduction_value: [10,6,3]
  aggregation_method: "prod"
dataset:
  name: "MNIST"
  number_of_classes: 10
options:
  threshold: 0.5
  number_of_trails: 20
  epochs: 100
  device: "cuda"
  name_of_the_run: "prod_freeze"
  add_reduction_layer: True
  model: "LaNet"
