hyperparameters:
  lr: [0.001]
  optimizers: ["Adam"]
  batchsize: [128]
  reduction_value: [3]
  aggregation_method: None
  prunning_val: [0]
dataset:
  name: "CIFAR100_K_CLASSES"
  num_classes: 80
options:
  number_of_trails: 10
  epochs: 200
  device: "cuda"
  name_of_the_run: "Cifar100"
  add_reduction_layer: True
  model: "CIFAR10"
  loss_function: "CrossEntropyLoss"
  save_model: True
  bias: False
